services:
  - type: web
    name: weather-app
    env: python
    buildCommand: |
      # Build frontend
      cd my-app && npm install && npm run build && cd ..
      # Install backend dependencies
      pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
