services:
  - type: web
    name: weather-app
    env: python
    buildCommand: |
      # Navigate to the frontend directory and build the React app
      cd frontend/my-app && npm install && npm run build && cd ../..
      # Install backend dependencies
      cd backend && pip install -r requirements.txt && cd ..
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
